services:
  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    container_name: users-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=identity_users
      - AUTH_SECRET=supersecretkey123
    depends_on:
      database:
        condition: service_healthy

  trains-service:
    build:
      context: .
      dockerfile: trains-service/Dockerfile
    container_name: trains-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=trains_db
      - MQTT_BROKER=tcp://server_mosquitto:1883
      - AUTH_SECRET=supersecretkey123
    depends_on:
      database:
        condition: service_healthy
      server_mosquitto:
        condition: service_started

  tickets-service:
    build:
      context: .
      dockerfile: tickets-service/Dockerfile
    container_name: tickets-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=tickets_db
      - AUTH_SECRET=supersecretkey123
    depends_on:
      database:
        condition: service_healthy

  notifications-service:
    build:
      context: .
      dockerfile: notifications-service/Dockerfile
    container_name: notifications-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=identity_subscriptions
      - MQTT_BROKER_URL=tcp://server_mosquitto:1883
      - AUTH_SECRET=supersecretkey123
    depends_on:
      database:
        condition: service_healthy
      server_mosquitto:
        condition: service_started

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=identity_users   # usa lo stesso DB dello users service
      - AUTH_SECRET=supersecretkey123
    depends_on:
      database:
        condition: service_healthy

  database:
    build: ./database
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecret" ]
      timeout: 20s
      retries: 10

  server_mosquitto:
    image: eclipse-mosquitto
    container_name: server_mosquitto
    ports:
      - "1884:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL_USERS=http://localhost:8081
        - VITE_API_URL_TRAINS=http://localhost:8082
        - VITE_API_URL_TICKETS=http://localhost:8083
        - VITE_API_URL_NOTIFICATIONS=http://localhost:8084
        - VITE_API_URL_AUTH=http://localhost:8085
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - users-service
      - trains-service
      - tickets-service
      - notifications-service
      - auth-service
volumes:
  db_data:
