services:
  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    container_name: users-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=identity_users
    depends_on:
      database:
        condition: service_healthy

  trains-service:
    build:
      context: .
      dockerfile: trains-service/Dockerfile
    container_name: trains-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=trains_db
    depends_on:
      database:
        condition: service_healthy

  tickets-service:
    build:
      context: .
      dockerfile: tickets-service/Dockerfile
    container_name: tickets-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=tickets_db
    depends_on:
      database:
        condition: service_healthy

  notifications-service:
    build:
      context: .
      dockerfile: notifications-service/Dockerfile
    container_name: notifications-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=identity_subscriptions
      - MQTT_BROKER_URL=tcp://mosquitto:1884
    depends_on:
      database:
        condition: service_healthy
      server_mosquitto:
        condition: service_started

  database:
    build: ./database
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecret" ]
      timeout: 20s
      retries: 10

  server_mosquitto:
    image: eclipse-mosquitto
    container_name: server_mosquitto
    ports:
      - "1884:1884"
    restart: unless-stopped

volumes:
  db_data:
