name: Go CI

on:
  push:
    branches: [ "develop", "feature/**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            user-service/.cache/go-build
            user-service/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('users-services/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./users-services
        run: go mod tidy

      - name: Build
        working-directory: ./users-services
        run: go build ./...

      - name: Run tests
        working-directory: ./users-services
        run: go test ./... -v

  trains-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            trains-service/.cache/go-build
            trains-service/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('trains-services/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./trains-services
        run: go mod tidy

      - name: Build
        working-directory: ./trains-services
        run: go build ./...

      - name: Run tests
        working-directory: ./trains-services
        run: go test ./... -v

  tickets-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            tickets-service/.cache/go-build
            tickets-service/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('tickets-services/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./tickets-services
        run: go mod tidy

      - name: Build
        working-directory: ./tickets-services
        run: go build ./...

      - name: Run tests
        working-directory: ./tickets-services
        run: go test ./... -v

  notifications-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            notifications-service/.cache/go-build
            notifications-service/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('notifications-services/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./notifications-services
        run: go mod tidy

      - name: Build
        working-directory: ./notifications-services
        run: go build ./...

      - name: Run tests
        working-directory: ./notifications-services
        run: go test ./... -v